version: ci-{build}
os: Visual Studio 2015

configuration:
  - Release

before_build:
  - utils\premake5 install_cef
  - utils\premake5 vs2015

after_build:
  - utils\premake5 install_data
  - utils\premake5 compose_files

clone_depth: 1

build:
  parallel: true
  project: Build/MTASA.sln
  
notifications:
  - provider: Slack
    incoming_webhook:
      secure: GMy2h7KrBeqM46INusj3AEZvef5jyFQRUeKqcJjfttHc/Iujje6YN398t7mo5UeMZjkDN2azgcb/R79wU/BvJot8iiu/4AtEBGwLffzrpCw=

artifacts:
  - path: InstallFiles
    name: MTASA
